FROM node:12.4.0-alpine as dev

RUN mkdir /work/
RUN mkdir /app/
RUN mkdir /app/build/
WORKDIR /app/

COPY ./consume-api/package.json /app/

#RUN npm install
RUN npm i -g serve

COPY ./consume-api/build/ /app/build/

#CMD ["npm","start"]
CMD ["serve","-s","build"]

