# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DevOps CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing node dependencies ...
      run: |
        cd nodejs/consume-api
        npm ci
    - name: Build apps ...
      run: |
        cd nodejs/consume-api
        npm run build --if-present
      env:
        CI: false
    - name: Test node apps ...
      run: |
        cd nodejs/consume-api
        npm test
    - name: Create Docker Package ...
      run: |
        docker-compose build
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        docker push smarttvminix/consume-api
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Telgram Notification Bot ...
      env:
        CIIOTBOT: ${{ secrets.CIIOTBOT }}
      run: |
        pwd
        ls -al
        chmod +x ./notify.sh
        ls -al
        ./notify.sh $CIIOTBOT
